/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "#f5c518",
        "outline": "#9a9078",
        "inverse-surface": "#e0e3e0",
        "on-primary-fixed-variant": "#584400",
        "secondary-fixed-dim": "#81da8e",
        "surface-variant": "#323633",
        "on-secondary-fixed": "#002109",
        "primary-fixed": "#ffe08b",
        "surface-container-lowest": "#0b0f0d",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-background": "#e0e3e0",
        "on-primary-container": "#695200",
        "surface-container-highest": "#323633",
        "on-primary-fixed": "#241a00",
        "tertiary-fixed": "#9af7aa",
        "secondary-fixed": "#9df7a8",
        "surface-container-high": "#272b29",
        "tertiary-fixed-dim": "#7eda90",
        "error": "#ffb4ab",
        "secondary-container": "#00682b",
        "secondary": "#81da8e",
        "on-secondary": "#003914",
        "surface-tint": "#f0c110",
        "surface-container-low": "#181c1a",
        "on-tertiary-container": "#00632c",
        "surface-bright": "#363a38",
        "primary": "#ffe5a0",
        "tertiary": "#9efcae",
        "surface-container": "#1c201e",
        "on-tertiary-fixed-variant": "#005323",
        "on-tertiary-fixed": "#00210a",
        "on-tertiary": "#003916",
        "surface": "#101412",
        "surface-dim": "#101412",
        "inverse-primary": "#745b00",
        "on-primary": "#3d2f00",
        "on-secondary-fixed-variant": "#005320",
        "primary-fixed-dim": "#f0c110",
        "on-surface-variant": "#d1c5ac",
        "background": "#101412",
        "on-error-container": "#ffdad6",
        "on-surface": "#e0e3e0",
        "on-secondary-container": "#8ce598",
        "inverse-on-surface": "#2d312f",
        "tertiary-container": "#83df94",
        "outline-variant": "#4e4633",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-desktop": "1rem",
        "margin-desktop": "1.25rem",
        "margin": "1rem",
        "space-lg": "1rem",
        "gutter": "0.75rem",
        "space-xl": "1.5rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "label-lg": ["JetBrains Mono", "monospace"],
        "body-lg": ["Work Sans", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Work Sans", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-lg": ["13px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-sm": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "12px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
